# Generated by Django 5.2.11 on 2026-02-24 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name_plural": "Customers"},
        ),
        migrations.AlterModelOptions(
            name="leadsource",
            options={"verbose_name_plural": "Lead Sources"},
        ),
        migrations.AddField(
            model_name="customer",
            name="data_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="lead_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("New", "New"),
                    ("Ongoing", "Ongoing"),
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Closed", "Closed"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.country",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="lead_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="lead_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.leadsource",
            ),
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("close_date", models.DateField(blank=True, null=True)),
                ("stage", models.CharField(max_length=255)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Deals",
            },
        ),
    ]
