# Generated by Django 5.2.11 on 2026-02-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_country_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="stage",
        ),
        migrations.AddField(
            model_name="deal",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open", "Open"),
                    ("Ongoing", "Ongoing"),
                    ("Closed", "Closed"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
