# Generated by Django 5.2.11 on 2026-02-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_remove_deal_stage_deal_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
